---
kind: "Deployment"
apiVersion: "apps/v1"
metadata: 
  name: "goku-studio-frontend"
  namespace: "aios"
  labels: 
    app: "goku-studio-frontend"
spec: 
  replicas: 0
  selector: 
    matchLabels: 
      app: "goku-studio-frontend"
  template: 
    metadata: 
      creationTimestamp: null
      labels: 
        app: "goku-studio-frontend"
    spec: 
      containers: 
        - 
          name: "goku-studio-frontend"
          image: "gcr.io/sre-common-test-379805/aios/goku-studio-frontend:sha-e82d8db"

